### ISSUE TITLE
'substeps' ordered lists should have a..z bullets

### ISSUE THREAD

**Issue by smhdfdl** [ot4i/ot4i.tutorials#34]
If bothy steps and substeps are ordered you end up with nested ordered lists that use the same numbering 1..9 and look confusing in the view.  KC uses 1..9 for outer then a..z for inner.

**Comment by cathyyoung** [comment]
Hi Steve - this is a quick fix that can be defined in CSS for nested ol lists, so you won't need to update your template or json file.

**Comment by smhdfdl** [comment]
Sounds good

**Comment by cathyyoung** [comment]
Fixed in iib-tutorials by 0c19aa88a88ad0a963cf12694be02c1169fe9c9e
Steve, we've migrated the src templates and media to iib-tutorials (ot4i.tutorials shouldn't be the repo for this) so the absolute URLs to the CSS, JS and images point to iib-tutorials in the templates.

**Comment by smhdfdl** [comment]
Cathy my tests from the toolkit are not picking this change up?

**Comment by smhdfdl** [comment]
Working now
